openapi: 3.0.3
info:
  title: Gene2Phenotype (G2P)
  version: 3.0.0
  description: Accelerating genomic medicine with high confidence evidence based gene
    disease models
paths:
  /gene2phenotype/api/lgd/{stable_id}/:
    get:
      operationId: lgd_retrieve
      description: |2

        Fetch detailed information about a specific record using the G2P stable ID.

        A record is a unique collection of Locus-Genotype-Mechanism-Disease-Evidence (LGMDE).
      parameters:
      - in: path
        name: stable_id
        schema:
          type: string
        required: true
      tags:
      - G2P record
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocusGenotypeDisease'
              examples:
                Example1:
                  value:
                    locus:
                      gene_symbol: FBN1
                      sequence: '15'
                      start: 48408313
                      end: 48645721
                      strand: -1
                      reference: grch38
                      ids:
                        HGNC: HGNC:3603
                        Ensembl: ENSG00000166147
                        OMIM: '134797'
                      synonyms:
                      - FBN
                      - MASS
                      - MFS1
                      - OCTD
                      - SGS
                      - WMS
                    stable_id: G2P02104
                    genotype: monoallelic_autosomal
                    variant_consequence:
                    - variant_consequence: altered gene product structure
                      accession: SO:0002318
                      support: inferred
                      publication: null
                    molecular_mechanism:
                      mechanism: undetermined
                      mechanism_support: inferred
                      synopsis: []
                      evidence: {}
                    disease:
                      name: FBN1-related isolated ectopia lentis
                      ontology_terms:
                      - accession: '129600'
                        term: ECTOPIA LENTIS 1, ISOLATED, AUTOSOMAL DOMINANT
                        description: null
                        source: OMIM
                      synonyms: []
                    confidence: limited
                    publications:
                    - publication:
                        pmid: 22539873
                        title: A novel FBN1 mutation in a Chinese family with isolated
                          ectopia lentis.
                        authors: Yang G, Chu M, Zhai X, Zhao J.
                        year: '2012'
                        comments: []
                        families: []
                    - publication:
                        pmid: 8136837
                        title: Mutations in the fibrillin gene responsible for dominant
                          ectopia lentis and neonatal Marfan syndrome.
                        authors: Kainulainen K, Karttunen L, Puhakka L, Sakai L, Peltonen
                          L.
                        year: '1994'
                        comments: []
                        families: []
                    - publication:
                        pmid: 7802039
                        title: Clinical and linkage study of a large family with simple
                          ectopia lentis linked to FBN1.
                        authors: Edwards MJ, Challinor CJ, Colley PW, Roberts J, Partington
                          MW, Hollway GE, Kozman HM, Mulley JC.
                        year: '1994'
                        comments: []
                        families: []
                    panels:
                    - name: Eye
                      description: Eye disorders
                    - name: Skin
                      description: Skin disorders
                    cross_cutting_modifier:
                    - term: restricted mutation set
                    variant_type:
                    - term: missense_variant
                      accession: SO:0001583
                      inherited: false
                      de_novo: false
                      unknown_inheritance: false
                      publications: []
                      comments: []
                    - term: inframe_deletion
                      accession: SO:0001822
                      inherited: false
                      de_novo: false
                      unknown_inheritance: false
                      publications: []
                      comments: []
                    - term: inframe_insertion
                      accession: SO:0001821
                      inherited: false
                      de_novo: false
                      unknown_inheritance: false
                      publications: []
                      comments: []
                    variant_description: []
                    phenotypes:
                    - term: Ectopia lentis
                      accession: HP:0001083
                      publications: []
                    - term: Autosomal dominant inheritance
                      accession: HP:0000006
                      publications: []
                    phenotype_summary: []
                    last_updated: '2024-08-20'
                    date_created: null
                    comments: []
                    curators:
                    - Elena Cibrian
                    is_reviewed: 1
                  summary: Example 1
                  description: Fetch detailed information for record 'G2P02104'
          description: ''
  /gene2phenotype/api/search/:
    get:
      operationId: search_list
      description: |2

        Search G2P records.
        Supported search types are:

            gene
            disease
            phenotype
            g2p_id

        If no search type is specified then it performs a generic search.
        The search can be specific to one panel if using parameter 'panel'.

        Example: `search/?type=gene&query=RHO&panel=Cancer`
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - in: query
        name: panel
        schema:
          type: string
        description: Fetch only records associated with a specific panel
      - in: query
        name: query
        schema:
          type: string
        description: Search term
        required: true
      - in: query
        name: type
        schema:
          type: string
        description: 'Type of search can be: gene, disease, phenotype or g2p_id'
      tags:
      - Search records
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                required:
                - count
                - results
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        gene:
                          type: string
                        genotype:
                          type: string
                        disease:
                          type: string
                        mechanism:
                          type: string
                        panel:
                          type: array
                          items:
                            type: string
                        confidence:
                          type: string
              examples:
                SearchByPhenotype:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - id: G2P01947
                      gene: ADAMTS10
                      genotype: biallelic_autosomal
                      disease: ADAMTS10-related Weill-Marchesani syndrome
                      mechanism: loss of function
                      panel:
                      - Eye
                      - Skin
                      confidence: definitive
                  summary: Search by phenotype
                  description: Search G2P records associated with phenotype HP:0003416
                SearchByGene:
                  value:
                    count: 123
                    next: http://api.example.org/accounts/?page=4
                    previous: http://api.example.org/accounts/?page=2
                    results:
                    - id: G2P01830
                      gene: TP53
                      genotype: monoallelic_autosomal
                      disease: TP53-related Li-Fraumeni syndrome
                      mechanism: loss of function
                      panel:
                      - Cancer
                      confidence: definitive
                  summary: Search by gene
                  description: Search G2P records associated with gene TP53
          description: Search response
  /gene2phenotype/api/panels/:
    get:
      operationId: panels_retrieve
      description: |2

        Fetch all G2P panels information.
      tags:
      - Fetch all panel disorders
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        description:
                          type: string
                        stats:
                          type: object
                          properties:
                            total_records:
                              type: integer
                            total_genes:
                              type: integer
                            by_confidence:
                              type: object
                              properties:
                                definitive:
                                  type: integer
                                strong:
                                  type: integer
                                limited:
                                  type: integer
                                moderate:
                                  type: integer
                                refuted:
                                  type: integer
                        last_updated:
                          type: string
                  count:
                    type: integer
              examples:
                Example:
                  value:
                    results:
                    - name: Cancer
                      description: Cancer disorders
                      stats:
                        total_records: 129
                        total_genes: 116
                        by_confidence:
                          definitive: 97
                          moderate: 14
                          strong: 10
                          limited: 8
                      last_updated: '2025-04-23'
                    - name: Cardiac
                      description: Cardiac disorders
                      stats:
                        total_records: 80
                        total_genes: 54
                        by_confidence:
                          strong: 6
                          definitive: 66
                          moderate: 8
                      last_updated: '2025-03-07'
                    - name: DD
                      description: Developmental disorders
                      stats:
                        total_records: 2768
                        total_genes: 2457
                        by_confidence:
                          definitive: 1482
                          strong: 726
                          limited: 374
                          moderate: 185
                          refuted: 1
                      last_updated: '2025-04-11'
          description: Panels response
  /gene2phenotype/api/panel/{name}/:
    get:
      operationId: panel_retrieve
      description: |2

        Fetch information for a specific panel by using its short name as the parameter.

        The response provides summary statistics about the records associated with it.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - Fetch individual panel disorder
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  last_updated:
                    type: string
                  stats:
                    type: object
                    properties:
                      total_records:
                        type: integer
                      total_genes:
                        type: integer
                      by_confidence:
                        type: object
                        properties:
                          definitive:
                            type: integer
                          strong:
                            type: integer
                          limited:
                            type: integer
                          moderate:
                            type: integer
                          refuted:
                            type: integer
              examples:
                DDPanel:
                  value:
                    name: DD
                    description: Developmental disorders
                    last_updated: '2025-04-11'
                    stats:
                      total_records: 2768
                      total_genes: 2457
                      by_confidence:
                        definitive: 1482
                        strong: 726
                        limited: 374
                        moderate: 185
                        refuted: 1
                  summary: DD panel
                  description: Fetch details for Developmental disorders (DD) panel
          description: Panel detail response
  /gene2phenotype/api/panel/{name}/summary/:
    get:
      operationId: panel_summary_retrieve
      description: |2

        Fetch latest records associated with a specific panel by using its short name as the parameter.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - Fetch individual panel disorder
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  panel_name:
                    type: string
                  records_summary:
                    type: object
                    properties:
                      locus:
                        type: string
                      disease:
                        type: string
                      genotype:
                        type: string
                      confidence:
                        type: string
                      variant_consequence:
                        type: array
                        items:
                          type: string
                      variant_type:
                        type: array
                        items:
                          type: string
                      molecular_mechanism:
                        type: string
                      last_updated:
                        type: string
                      stable_id:
                        type: string
              examples:
                DDPanel:
                  value:
                    panel_name: DD
                    records_summary:
                    - locus: WASF1
                      disease: WASF1-related neurodevelopmental disorder
                      genotype: monoallelic_autosomal
                      confidence: limited
                      variant_consequence:
                      - decreased gene product level
                      variant_type:
                      - whole_partial_gene_deletion
                      molecular_mechanism: loss of function
                      last_updated: '2025-04-16'
                      stable_id: G2P03736
                    - locus: WASF1
                      disease: WASF1-related intellectual disability with seizures
                      genotype: monoallelic_autosomal
                      confidence: moderate
                      variant_consequence:
                      - absent gene product
                      - altered gene product structure
                      variant_type:
                      - missense_variant
                      - stop_gained_NMD_escaping
                      - frameshift_variant_NMD_escaping
                      - whole_partial_gene_deletion
                      molecular_mechanism: loss of function
                      last_updated: '2025-04-16'
                      stable_id: G2P02611
                    - locus: UBR5
                      disease: UBR5-related neurodevelopmental disorder
                      genotype: monoallelic_autosomal
                      confidence: moderate
                      variant_consequence:
                      - altered gene product structure
                      - decreased gene product level
                      variant_type:
                      - frameshift_variant
                      - stop_gained
                      - missense_variant
                      - inframe_deletion
                      - inframe_insertion
                      molecular_mechanism: loss of function
                      last_updated: '2025-04-16'
                      stable_id: G2P03734
                  summary: DD panel
                  description: Fetch latest records for DD panel
          description: Panel summary response
  /gene2phenotype/api/panel/{name}/download/:
    get:
      operationId: panel_download_retrieve
      description: |2

        Download all records associated with a specific panel by using its short name as the parameter.

        It returns an uncompressed csv file.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - Fetch individual panel disorder
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /gene2phenotype/api/gene/{name}/:
    get:
      operationId: gene_retrieve
      description: |2

        Fetch information for a specific gene by using the gene symbol.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - Fetch gene information
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocusGene'
              examples:
                GeneFBN1:
                  value:
                    gene_symbol: FBN1
                    sequence: '15'
                    start: 48408313
                    end: 48645721
                    strand: -1
                    reference: grch38
                    ids:
                      HGNC: HGNC:3603
                      Ensembl: ENSG00000166147
                      OMIM: '134797'
                    synonyms:
                    - FBN
                    - MASS
                    - MFS1
                    - OCTD
                    - SGS
                    - WMS
                    last_updated: '2025-03-24'
                  summary: gene FBN1
                  description: Fetch details for gene FBN1
          description: ''
  /gene2phenotype/api/gene/{name}/summary/:
    get:
      operationId: gene_summary_retrieve
      description: |2

        Fetch latest records associated with a specific gene by using the gene symbol.
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - Fetch gene records summary
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  gene_symbol:
                    type: string
                  records_summary:
                    type: array
                    items:
                      type: object
                      properties:
                        disease:
                          type: string
                        genotype:
                          type: string
                        confidence:
                          type: string
                        panels:
                          type: array
                          items:
                            type: string
                        variant_consequence:
                          type: array
                          items:
                            type: string
                        variant_type:
                          type: array
                          items:
                            type: string
                        molecular_mechanism:
                          type: string
                        last_updated:
                          type: string
                        stable_id:
                          type: string
              examples:
                GeneFBN1:
                  value:
                    gene_symbol: FBN1
                    records_summary:
                    - disease: FBN1-related isolated ectopia lentis
                      genotype: monoallelic_autosomal
                      confidence: limited
                      panels:
                      - Eye
                      - Skin
                      variant_consequence:
                      - altered gene product structure
                      variant_type:
                      - missense_variant
                      - inframe_deletion
                      - inframe_insertion
                      molecular_mechanism: undetermined
                      last_updated: '2024-08-20'
                      stable_id: G2P02104
                    - disease: FBN1-related Weill-Marchesani syndrome
                      genotype: monoallelic_autosomal
                      confidence: strong
                      panels:
                      - DD
                      - Eye
                      - Skin
                      - Skeletal
                      variant_consequence:
                      - altered gene product structure
                      variant_type:
                      - missense_variant
                      - inframe_deletion
                      - inframe_insertion
                      molecular_mechanism: undetermined
                      last_updated: '2024-08-20'
                      stable_id: G2P01563
                    - disease: FBN1-related Marfan syndrome
                      genotype: biallelic_autosomal
                      confidence: definitive
                      panels:
                      - DD
                      - Eye
                      - Skin
                      - Skeletal
                      variant_consequence:
                      - absent gene product
                      - altered gene product structure
                      variant_type:
                      - splice_region_variant
                      - frameshift_variant
                      - missense_variant
                      molecular_mechanism: loss of function
                      last_updated: '2024-05-13'
                      stable_id: G2P03125
                    - disease: FBN1-related Marfan syndrome
                      genotype: monoallelic_autosomal
                      confidence: definitive
                      panels:
                      - DD
                      - Eye
                      - Skin
                      - Skeletal
                      variant_consequence:
                      - absent gene product
                      - altered gene product structure
                      variant_type: []
                      molecular_mechanism: loss of function
                      last_updated: '2023-05-24'
                      stable_id: G2P01013
                  summary: gene FBN1
                  description: Fetch latest records associated with gene FBN1
          description: Gene summary response
  /gene2phenotype/api/disease/{id}/summary/:
    get:
      operationId: disease_summary_retrieve
      description: |2

        Fetch latest records associated with a specific disease.

        The disease input can be a disease name or ontology ID (e.g. Mondo or OMIM).
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Fetch disease records summary
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  disease:
                    type: string
                  records_summary:
                    type: array
                    items:
                      type: object
                      properties:
                        locus:
                          type: string
                        genotype:
                          type: string
                        confidence:
                          type: string
                        panels:
                          type: array
                          items:
                            type: string
                        variant_consequence:
                          type: array
                          items:
                            type: string
                        variant_type:
                          type: array
                          items:
                            type: string
                        molecular_mechanism:
                          type: string
                        stable_id:
                          type: string
              examples:
                MONDO:0008913:
                  value:
                    disease: MONDO:0008913
                    records_summary:
                    - locus: PLD1
                      genotype: biallelic_autosomal
                      confidence: definitive
                      panels:
                      - DD
                      variant_consequence:
                      - absent gene product
                      variant_type:
                      - splice_donor_variant
                      - frameshift_variant
                      - stop_gained
                      - missense_variant
                      molecular_mechanism: loss of function
                      stable_id: G2P03704
                  description: Fetch records linked to disease 'MONDO:0008913'
          description: Disease summary response
  /gene2phenotype/api/disease/{id}/:
    get:
      operationId: disease_retrieve
      description: |2

        Fetch information for a specific disease.

        The disease input can be a disease name or ontology ID (e.g. Mondo or OMIM).
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - Fetch disease information
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiseaseDetail'
              examples:
                MONDO:0008913:
                  value:
                    name: PLD1-related cardiac valvular dysplasia
                    ontology_terms:
                    - accession: '212093'
                      term: CARDIAC VALVULAR DYSPLASIA 1
                      description: CARDIAC VALVULAR DYSPLASIA 1
                      source: OMIM
                    - accession: MONDO:0008913
                      term: cardiac valvular defect, developmental
                      description: cardiac valvular defect, developmental
                      source: Mondo
                    synonyms: []
                    last_updated: '2025-02-19'
                  description: Fetch information for disease 'MONDO:0008913'
          description: ''
  /gene2phenotype/api/reference_data/:
    get:
      operationId: reference_data_retrieve
      description: |2

        Fetch list of all reference data used in G2P with their respective versions.
      tags:
      - Reference data
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    source:
                      type: string
                    version:
                      type: string
          description: Reference data response
components:
  schemas:
    DiseaseDetail:
      type: object
      description: Serializer for the Disease model - extra fields.
      properties:
        name:
          type: string
        ontology_terms:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: Returns the ontology terms associated with the disease.
          readOnly: true
        synonyms:
          type: array
          items:
            type: string
          description: Returns disease synonyms used in other sources.
          readOnly: true
        last_updated:
          type: string
          format: date
          nullable: true
          description: Returns the date an entry linked to the disease has been updated.
          readOnly: true
      required:
      - last_updated
      - name
      - ontology_terms
      - synonyms
    LocusGene:
      type: object
      description: |-
        Serializer for the LocusSerializer model extra data.
        It returns the Locus data and the date of the last update.
        It can also include:
         - summary of records associated with the locus (method records_summary)
         - gene product function from UniProt (method function)
      properties:
        gene_symbol:
          type: string
        sequence:
          type: string
        start:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        end:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        strand:
          type: integer
          maximum: 32767
          minimum: -32768
        reference:
          type: string
          readOnly: true
        ids:
          type: object
          additionalProperties:
            type: string
          description: |-
            Locus IDs from external sources.
            It can be the HGNC ID for a gene.
          readOnly: true
        synonyms:
          type: array
          items:
            type: string
          description: |-
            Returns the locus synonyms.
            The locus synonym can be an old gene symbol.
          readOnly: true
        last_updated:
          type: string
          format: date
          nullable: true
          description: Returns the date last time the locus was updated.
          readOnly: true
      required:
      - end
      - gene_symbol
      - ids
      - last_updated
      - reference
      - sequence
      - start
      - synonyms
    LocusGenotypeDisease:
      type: object
      description: |-
        Serializer for the LocusGenotypeDisease model.
        LocusGenotypeDisease represents a G2P record.
      properties:
        locus:
          type: object
          additionalProperties: {}
          description: |-
            Locus linked to the LGD record.
            It can be a gene, variant or region.
          readOnly: true
        stable_id:
          type: string
          readOnly: true
        genotype:
          type: string
          readOnly: true
        variant_consequence:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            Variant consequences linked to the LGD record.
            This is the GenCC level of variant consequence: altered_gene_product_level, etc.
          readOnly: true
          nullable: true
        molecular_mechanism:
          type: object
          additionalProperties: {}
          description: |-
            Molecular mechanism associated with the LGD record.
            If available, also returns the evidence.
          readOnly: true
          nullable: true
        disease:
          type: object
          additionalProperties: {}
          description: Disease associated with the LGD record.
          readOnly: true
        confidence:
          type: string
        publications:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
              additionalProperties: {}
          description: Publications associated with the LGD record.
          readOnly: true
        panels:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
          description: Panel(s) associated with the LGD record.
          readOnly: true
        cross_cutting_modifier:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
          description: Cross cutting modifier terms associated with the LGD record.
          readOnly: true
          nullable: true
        variant_type:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            Variant types associated with the LGD record.
            The variant type can be linked to several publications therefore response
            includes the list of publications associated with the variant type.
          readOnly: true
          nullable: true
        variant_description:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            Variant HGVS description linked to the LGD record and publication(s).
            The response includes a list of publications associated with the HGVS description.
          readOnly: true
          nullable: true
        phenotypes:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            Phenotypes associated with the LGD record.
            The response includes the list of publications associated with the phenotype.
          readOnly: true
          nullable: true
        phenotype_summary:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            A summary about the phenotypes associated with the LGD record.
            The response includes the publication associated with the summary.
          readOnly: true
          nullable: true
        last_updated:
          type: string
          nullable: true
          description: Date last time the LGD record was updated by a curator.
          readOnly: true
        date_created:
          type: string
          format: date
          nullable: true
          description: |-
            Date the LGD record was created.
            Dependency: this method depends on the history table.

            Note: entries that were migrated from the old db don't have the date when they were created.
          readOnly: true
        comments:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: |-
            LGD record comments.
            Comments can be public or private. Private comments can only be
            seen by curators.
          readOnly: true
          nullable: true
        curators:
          type: array
          items:
            type: string
          description: |-
            List of curators who worked on the LGD record.
            Dependency: this method depends on the history table.

            Note: entries that were migrated from the old db have limited info details.
          readOnly: true
          nullable: true
        is_reviewed:
          type: integer
          nullable: true
      required:
      - comments
      - confidence
      - cross_cutting_modifier
      - curators
      - date_created
      - disease
      - genotype
      - last_updated
      - locus
      - molecular_mechanism
      - panels
      - phenotype_summary
      - phenotypes
      - publications
      - stable_id
      - variant_consequence
      - variant_description
      - variant_type
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
